name: Dev

on:
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install requirements
        run: |
          pip install -U pip wheel setuptools
          pip install -q -r requirements/deploifai.txt -r requirements/cli.txt -r requirements/dev.txt

      - name: Run tests
        run: echo "No tests yet"

  build:
    needs: test
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install requirements
        run: |
          pip install -U pip wheel setuptools
          pip install -q -r requirements/deploifai.txt -r requirements/cli.txt -r requirements/dev.txt

      - name: Build distribution packages
        run: python -m build
