name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install requirements
        run: pip3 install -q -r requirements.txt

      - name: Build distribution packages
        run: python3 -m build

      - name: Release to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_TOKEN }}
        run: twine upload -r pypi --skip-existing dist/*
