name: Release

on:
  release:
    types:
      - published

jobs:
  pypi:
    name: pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Install requirements
        run: |
          pip install -U pip wheel setuptools
          pip install -q -r requirements/deploifai.txt -r requirements/cli.txt -r requirements/dev.txt

      - name: Build distribution packages
        run: python -m build

      - name: Release to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_API_TOKEN }}
        run: twine upload -r pypi --skip-existing dist/*

  homebrew:
    name: homebrew
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch release event to homebrew-deploifai repo
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_GITHUB_ACTIONS }}
          repository: deploifai/homebrew-deploifai
          event-type: release
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "tag": "${{ github.event.release.tag_name }}", "version": "${{ github.event.release.tag_name }}"}'
